site_name: LendBook Documentation



nav:
  - Introduction | TLDR: index.md
  - What is LendBook ?: base-features/what-is-lendbook.md 
  - How it works?: #base-features/how-it-works.md 
    - Market participants: core-concepts/market-participants.md
    - Pools of orders: core-concepts/pools-of-orders.md
    - Main Rules: core-concepts/rules.md
    - Liquidation: core-concepts/liquidation.md
    - Interest Rates: core-concepts/interest-rates.md
  - .:
    - Lender: user-lender/lender.md
  - Borrower: user-borrower/borrower.md
  - Lender: user-lender/lender.md
  - Taker: user-taker/taker.md 
  - Benefits for market participants: 
    - Borrowers: borrower/benefits-borrower.md
    - Lenders: lender/benefits-lender.md
    - Takers: lender/benefits-lender.md
  - Use Cases: lender/benefits-lender.md
  - Advantages:
    - stop loss: lender/benefits-lender.md
    - AAA: lender/benefits-lender.md




theme:
  name: material
  logo: "images/logo_white.png"
  favicon: "images/logo_white.png"
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections # in order to see all the sections at the same time (prefer not to use it)
    - navigation.expand #(to see all the sections when .sections is unable)
    - navigation.instant
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode   
      primary: custom
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode 
      primary: custom
      accent: lime



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lendbook
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/lend_book


repo_name: LendBook/lendbook-docs
repo_url: https://github.com/LendBook/lendbook-docs
