site_name: LendBook Documentation



nav:
  - Getting Started:
    - Understanding LLOB: base-features/understanding-llob.md  
  - Borrower:
    - Understanding Borrowing: borrower/understanding-borrowing.md



theme:
  name: material
  logo: "images/logo_white.png"
  favicon: "images/logo_white.png"
  features:
    - navigation.sections # in order to see all the sections at the same time (prefer not to use it)
    #- navigation.expand (to see all the sections when .sections is unable)
    - navigation.instant
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: lime



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lendbook
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/lend_book


repo_name: LendBook/lendbook-docs
repo_url: https://github.com/LendBook/lendbook-docs
