site_name: LendBook Documentation



nav:
  - Introduction:
    - What is LendBook ?: index.md
    - TL;DR: introduction/tldr.md 
  - How it works?: #base-features/how-it-works.md 
    - Market participants: how-it-works/market-participants.md
    - Pools of orders: how-it-works/pools-of-orders.md
    - Main Rules: how-it-works/rules.md
    - Interest Rates: how-it-works/interest-rates.md
    - Liquidation fees:  how-it-works/liquidation.md
    - Max Loan-To-Value:  how-it-works/max-loan-to-value.md
  - Users:
    - Borrower: users/borrower.md
    - Lender: users/lender.md
    - Taker: users/taker.md 
  - Advantages of LendBook: 
    - No bad debt / No off-chain risk management: advantages/risk-management.md
    - Simple debt management: advantages/debt-management.md
    - Stop loss and take profit: advantages/stop-loss-take-profit.md
    - Low liquidation cost: advantages/liquidation-cost.md
    - High Loan-To-Value: advantages/loan-to-value.md
    - High leverage: advantages/leverage.md
    - Soft-pegged assets: advantages/soft-pegged-assets.md
    - Automated Market Making: advantages/automated-market-making.md
    - Addressable market: advantages/addressable-market.md
    - Minimized governance: advantages/governance.md
    #- Degen Strategies : borrow USDC with USDC as collateral
  - Others :
    - Questions/feedbacks: others/questions.md




theme:
  name: material
  logo: "images/logo.png"
  favicon: "images/logo.png"
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections # in order to see all the sections at the same time (prefer not to use it)
    - navigation.expand #(to see all the sections when .sections is unable)
    - navigation.instant
    - navigation.footer
    #- toc.integrate # in order to show subtitles in the sidebars (I prefer to hide the subtitles)
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode   
      primary: custom
      accent: custom
    - scheme: slate  #dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode 
      primary: custom
      accent: custom



markdown_extensions:
  - tables
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lendbook
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/lend_book


repo_name: LendBook/lendbook-docs
repo_url: https://github.com/LendBook/lendbook-docs


watch:
  - includes